name: Build & Release

on:
  push:
    branches:
      - "main"
      - "feature/*"
  pull_request:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: cargo build -r --verbose

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Binary
          path: |
            target/release/fs_compare
            target/release/fs_state_gen
            target/release/run_rsync

